IF OBJECT_ID('dbo.Question','U') IS NULL
BEGIN
	CREATE TABLE Question (
		Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		Title VARCHAR(50) NOT NULL,
		Description VARCHAR(MAX) NOT NULL,
		UpvoteCount INT NOT NULL DEFAULT 0,
		DownvoteCount INT NOT NULL DEFAULT 0,
		UserName VARCHAR(20) NOT NULL,
		Email VARCHAR(50) NOT NULL,
		PostedOn DATETIME NOT NULL DEFAULT GETDATE(),
		UpdatedOn DATETIME NULL
	)
END

IF OBJECT_ID('dbo.Answer', 'U') IS NULL
BEGIN
	CREATE TABLE Answer (
		Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		QuestionId INT NOT NULL,
		Content VARCHAR(MAX) NOT NULL,
		UpvoteCount INT NOT NULL DEFAULT 0,
		DownvoteCount INT NOT NULL DEFAULT 0,
		UserName VARCHAR(20) NOT NULL,
		Email VARCHAR(50) NOT NULL,
		PostedOn DATETIME NOT NULL DEFAULT GETDATE(),
		UpdatedOn DATETIME NULL
	)
END

IF OBJECT_ID('dbo.Comment', 'U') IS NULL
BEGIN
	CREATE TABLE Comment (
		Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		PostId INT NOT NULL,
		PostType VARCHAR(10) NOT NULL,
		Content VARCHAR(MAX) NOT NULL,
		UpvoteCount INT NOT NULL DEFAULT 0,
		--DownvoteCount INT NOT NULL DEFAULT 0,
		UserName VARCHAR(20) NOT NULL,
		Email VARCHAR(50) NOT NULL,
		PostedOn DATETIME NOT NULL DEFAULT GETDATE(),
		UpdatedOn DATETIME NULL
	)
END

IF OBJECT_ID('dbo.User', 'U') IS NULL
BEGIN
	CREATE TABLE [User] (
		Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		UserName VARCHAR(20) NOT NULL,
		Email VARCHAR(50) NOT NULL,
		Password VARCHAR(50) NOT NULL,
		RegisteredOn DATETIME NOT NULL DEFAULT GETDATE()
	)
END